-- Self check-in registration: what a guest enters and signs at the kiosk.
--
-- Run once in the Supabase SQL Editor. Until it has run, the kiosk's
-- registration screen still renders - it just can't save a signature or an
-- extra guest, and says so rather than failing silently.
--
-- DURABLE, never pruned, on purpose - the same rule the bcp_* tables follow:
-- a signed registration card is the property's own record of who signed what,
-- and the ร.ร.๓ (RR3) filing reads it back (sync_service.get_rr3_cards merges
-- the signature onto that guest's card). The per-minute kiosk_reservations_sync
-- mirror is the disposable half of the kiosk; this is the half that must not
-- be thrown away.
--
-- Why these live outside MEWS: the Connector API cannot take them. Measured
-- against Marasca Samui's own token on 18-Sep-2026 - customers/add,
-- customers/update, reservations/addCompanion and reservations/deleteCompanion
-- all answer 401 "No permission to use this operation", and there is no
-- attachment endpoint on the Connector API at all (files/add, documents/add
-- and reservations/addAttachment are each a 404 "Requested resource does not
-- exist"). serviceOrderNotes/add IS permitted, which is why a signed card
-- writes a short note back onto the reservation instead of a file.

-- One row per signature. Same shape as bcp_reg_cards (a reservation can have
-- several guests, each signing their own card) but kept separate from it:
-- bcp_reg_cards is specifically what front desk captured while MEWS was DOWN,
-- and mixing an ordinary self-service check-in into that record would
-- misrepresent both.
create table if not exists public.kiosk_reg_cards (
    id                  bigint generated by default as identity primary key,
    property            text        not null,
    reservation_number  text        not null,
    -- MEWS customer id for a guest MEWS already knows; for a guest added at
    -- the kiosk it is that guest's kiosk_extra_guests.guest_key instead.
    guest_key           text        not null,
    -- {"blob": encrypt(json)} - name, email, marketing consent, the signature
    -- PNG data URL. Whole-blob encrypted for the same reason the report
    -- tables are: the PII sits nested inside, where a flat per-field scan
    -- can't reach it.
    data                jsonb       not null,
    created_at          timestamptz not null default now()
);

create index if not exists kiosk_reg_cards_lookup_idx
    on public.kiosk_reg_cards (property, reservation_number, guest_key, created_at desc);

-- Guests added at the terminal who are not on the MEWS reservation. They
-- cannot be pushed to MEWS today (addCompanion is 401 - see above), so they
-- live here and are merged into the kiosk's guest list on read. If MEWS ever
-- enables the scope, this table is what a sync would replay from.
create table if not exists public.kiosk_extra_guests (
    id                  bigint generated by default as identity primary key,
    property            text        not null,
    reservation_number  text        not null,
    guest_key           text        not null,
    data                jsonb       not null,   -- {"blob": encrypt(json)} - first/last name
    created_at          timestamptz not null default now(),
    constraint kiosk_extra_guests_key unique (property, reservation_number, guest_key)
);

create index if not exists kiosk_extra_guests_lookup_idx
    on public.kiosk_extra_guests (property, reservation_number);

-- RLS decision: enabled, NO policies - backend-only, like every other table
-- holding guest PII. Reads and writes go through /api/kiosks/* with the
-- service role, which bypasses RLS. The rls_enabled_no_policy INFO lint this
-- produces is expected, not a gap.
alter table public.kiosk_reg_cards enable row level security;
alter table public.kiosk_extra_guests enable row level security;
