-- Manual corrections to a generated RR4/TM30 register, made at
-- RR4/TM30 > RR4 & TM30 Files > (RR4|TM30) > Edit.
--
-- Kept in its OWN table rather than being written back into the
-- rr4_tm30_sync blob, because "Re-Generate Files" and the nightly
-- auto-import both overwrite that blob wholesale: an edit stored in there
-- is silently un-done by the next regenerate, on a document that may
-- already have been filed with the district office. Storing corrections
-- separately also keeps "what MEWS said" and "what staff changed"
-- distinguishable after the fact, which is what you need when a filing is
-- queried.
--
-- One row per edited guest row. row_key is
-- "<ReservationId>:<CustomerId>" (or "<ReservationId>:placeholder:<n>" for
-- MEWS's unattached-companion slots) - stable across a re-import, unlike
-- the register's own positional line number.
--
-- data->>'blob' is a Fernet-encrypted JSON {column: value} map. Encrypted
-- for exactly the same reason the report blobs are: an override carries
-- precisely the PII the register does - guest names, passport and national
-- ID numbers, addresses.

create table if not exists public.rr4_tm30_overrides (
    id           bigint generated by default as identity primary key,
    property     text        not null,
    report_date  date        not null,
    kind         text        not null check (kind in ('rr4', 'tm30')),
    row_key      text        not null,
    data         jsonb       not null,
    updated_by   text,
    updated_at   timestamptz not null default now(),
    created_at   timestamptz not null default now(),
    constraint rr4_tm30_overrides_row_key unique (property, report_date, kind, row_key)
);

-- Every read is "all overrides for this one (property, date, kind)", which
-- is what apply_rr4_tm30_overrides asks for on every register build.
create index if not exists rr4_tm30_overrides_lookup_idx
    on public.rr4_tm30_overrides (property, report_date, kind);

-- RLS: ENABLED, with NO policies. This table is reached only through the
-- FastAPI backend, which connects with the service_role key and therefore
-- bypasses RLS entirely; enabling it with no policies makes the table
-- deny-by-default to the browser's anon key, which is public (it ships
-- inside the JS bundle). Same shape as st_files_sync / rv_files_sync /
-- bcp_* - and deliberately NOT the shape rr4_nationality_codes uses, which
-- the browser does read directly, because that table holds no PII and this
-- one holds guest passport numbers.
--
-- The Supabase default for a new table is RLS OFF - i.e. anon-key readable
-- by anyone on the internet - so this line is not optional.
alter table public.rr4_tm30_overrides enable row level security;
