-- RV (Revenue) file cache: one row per (property, report_date).
-- Mirrors st_files_sync - the whole report is Fernet-encrypted into
-- data->>'blob' because revenue lines quote guest/company names inside
-- billing descriptions, so per-field encryption wouldn't reach them.

create table if not exists public.rv_files_sync (
    id           bigint generated by default as identity primary key,
    property     text        not null,
    report_date  date        not null,
    data         jsonb       not null,
    synced_at    timestamptz not null default now(),
    created_at   timestamptz not null default now(),
    constraint rv_files_sync_property_date_key unique (property, report_date)
);

create index if not exists rv_files_sync_property_date_idx
    on public.rv_files_sync (property, report_date desc);

-- Per-AccountingCategoryId GL overrides. Optional: get_rv_report falls back
-- to BillingName matching when this table is empty or absent, so RV works
-- before anyone fills it in. Populate it once MEWS enables the Accounting
-- Categories permission on the Connector tokens.
create table if not exists public.rv_gl_mappings (
    id                      bigint generated by default as identity primary key,
    property                text not null,
    accounting_category_id  text not null,
    category_name           text,
    gl_code                 text not null,
    department              text,
    updated_at              timestamptz not null default now(),
    constraint rv_gl_mappings_property_category_key unique (property, accounting_category_id)
);

-- Sidebar gating for the new RV menu. Navigation.tsx reads role_permissions
-- with select("*") precisely so a missing column only hides that one link
-- instead of failing the whole query - so the app stays usable if this
-- hasn't run yet, and the menu simply appears once it has.
alter table public.role_permissions add column if not exists rv boolean not null default false;
update public.role_permissions set rv = true where role = 'Super Admin';

-- RLS: both new tables are reached ONLY through the FastAPI backend, which uses
-- the service_role key and therefore bypasses RLS entirely. Enabling RLS with
-- no policies makes them deny-by-default to the browser's anon key while
-- leaving the backend fully working. This is the opposite of role_permissions
-- (RLS deliberately OFF there, because the browser reads it directly).
alter table public.rv_files_sync enable row level security;
alter table public.rv_gl_mappings enable row level security;
